### ISSUE TITLE
/insight-api/addr/[addr] and /insight-api/tx/[txid] hangs for nonexisting address/txid

### ISSUE THREAD

**Issue by Antti-Kaikkonen** [dashpay/insight-api#23]
For example go to: https://insight.dash.org/insight-api/tx/test or https://insight.dash.org/insight-api/addr/test . Should return 404 but it hangs.

As a consequence the search functionality also isn't working properly in insight.dash.org.

**Comment by nmarley** [comment]
Yep, this is the root cause of https://github.com/dashevo/insight-ui/issues/20 . We need to revert the change which broke this.

**Comment by nmarley** [comment]
According to @gilemon, the root cause of the regression is the modifications on lib/common.js from : https://github.com/dashevo/insight-api/commit/f41f5e3f9a9d57cc3ba420566031358ab551edeb#diff-1ffb5a9090758229a335b02a477425c7R14

**Comment by nmarley** [comment]
Should be fixed by #25 , just waiting for review.

**Comment by snogcel** [comment]
In the event that this issue still persists wanted to drop some notes on a potential cause of this problem.

I noticed that lib/blocks.js was updated by this commit: https://github.com/dashevo/insight-api/commit/f41f5e3f9a9d57cc3ba420566031358ab551edeb#diff-697e451c79efbf72b039990a4f4e30a3

Prior to this commit the following evaluation (hash.length < 64 || !isHexadecimal(hash)) would result in:

return self.common.handleErrors(null, res); 

After this commit it is returning a specific error message instead of "null": 

return self.common.handleErrors(err, res);

This prevents 404 from being reported by the server as this response will only be triggered if err == null: https://github.com/dashevo/insight-api/blob/master/lib/common.js#L24. I think it may be causing issues with next() being called when it shouldn't be but haven't done hands on testing yet. If this is the case it could result in the empty "res.status" mentioned in #25. Let me know if this still needs attention and I can take a closer look / pull request.

**Comment by nmarley** [comment]
Ah, ok, perfect -- this is probably the reason this bug was introduced in the first place, trying to handle this situation. Thanks for helping get to root cause @snogcel !

Currently it appears the search should be fixed in insight-api v1.0.1 (including current DCG Insight deployment), but will keep this in mind if this `getBlockHeader` becomes an issue.

@Antti-Kaikkonen Your issue should now be fixed at the URLs you reported.

**Comment by nmarley** [comment]
Closing as issue has been fixed
